export enum EQuestionReportReason {
  WRONG_ANSWER = 'WRONG_ANSWER',
  TYPO = 'TYPO',
  WRONG_EXPLANATION = 'WRONG_EXPLANATION',
  INCORRECT_CONTENT = 'INCORRECT_CONTENT',
  MISSING_MEDIA = 'MISSING_MEDIA',
  OFFENSIVE_CONTENT = 'OFFENSIVE_CONTENT',
  OTHER = 'OTHER',
}
